keyworddict = {'San Francisco': 'San Francisco', 
				'Chicago':'Chicago', 
				'Utah':'Utah', 
				'California':'California', 
				'California Senator': 'California',
				'Pete Aguilar': 'Redlands',
				'John J. Allen': 'Oakland',
				'Glenn Anderson': 'Hawthorne',
				'Jack Anderson': 'San Juan Bautista',
				'Samuel Beach Axtel': 'San Francisco',
				'Stanford': 'Palo Alto',
				'California minimum wage': 'California',
				'oakland': 'oakland',
				'Kamala Harris': 'California', 
				'Dianne Feinstein':'California', 
				'Andreas Borgeas': 'California',
				'Mitt Romney': 'Utah',
				'Mike Lee': 'Utah',
				'Ben McAdams':'Salt Lake City',
				'Rob Bishop': 'Utah',
				' Chris Stewart': 'Utah',
				'John Curtis': 'Utah'}
