keyworddict = {'San Francisco': 'San Francisco', 
				'Chicago':'Chicago',
				'New York': 'New York City',
				'MTA': 'New York City',
				'Boston':'Boston':
				'Los Angles': 'Los Angeles',
				'Texas':'Texas', 
				'Utah':'Utah', 
				'Californian':'California', 
				'Pete Aguilar': 'Redlands',
				'John J. Allen': 'Oakland',
				'Glenn Anderson': 'Hawthorne',
				'Jack Anderson': 'San Juan Bautista',
				'Samuel Beach Axtel': 'San Francisco',
				'Stanford': 'Palo Alto',
				'California minimum wage': 'California',
				'oakland': 'oakland',
				'Kamala Harris': 'California', 
				'Dianne Feinstein':'California', 
				'Andreas Borgeas': 'California',
				'Mitt Romney': 'Utah',
				'Mike Lee': 'Utah',
				'Ben McAdams':'Salt Lake City',
				'Rob Bishop': 'Utah',
				'Chris Stewart': 'Utah',
				'John Curtis': 'Utah'}
